2023/10/27 10:27:39 failed to dial tcp connection, retrying
[2023-10-27T10:27:40.865Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-10-27T10:27:40.867Z] info  Using user-data-dir ~/.local/share/code-server
====================================>token: ce8f312a-4542-4139-8f0c-17d9d73ebc2e
[2023-10-27T10:27:40.883Z] info  Using config file ~/.config/code-server/config.yaml
[2023-10-27T10:27:40.883Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-10-27T10:27:40.883Z] info    - Authentication is disabled
[2023-10-27T10:27:40.883Z] info    - Not serving HTTPS
[10:27:42] 




[10:27:42] Extension host agent started.
[10:27:44] [127.0.0.1][0e15605a][ManagementConnection] New connection established.
[10:27:45] [127.0.0.1][29edceaf][ExtensionHostConnection] New connection established.
[10:27:45] [127.0.0.1][29edceaf][ExtensionHostConnection] <379> Launched Extension Host Process.
[10:27:48] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[10:27:59] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
[2023-10-27T10:29:53.974Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
[11:02:25] [File Watcher (node.js)] Failed to watch /opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py for changes using fs.watch() (Error: ENOSPC: System limit for number of file watchers reached, watch '/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py')
2023/10/27 13:57:43 exit program after timeout
