2023/12/08 00:13:39 failed to dial tcp connection, retrying
[2023-12-08T00:13:40.920Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-12-08T00:13:40.921Z] info  Using user-data-dir ~/.local/share/code-server
[2023-12-08T00:13:40.935Z] info  Using config file ~/.config/code-server/config.yaml
[2023-12-08T00:13:40.935Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-12-08T00:13:40.935Z] info    - Authentication is disabled
[2023-12-08T00:13:40.935Z] info    - Not serving HTTPS
====================================>token: dba5d911-27bb-4414-b12c-f64b34f2cf4b
[00:13:42] 




[00:13:42] Extension host agent started.
[00:13:45] [127.0.0.1][b1697ca3][ManagementConnection] New connection established.
[00:13:46] [127.0.0.1][b4abf3d3][ExtensionHostConnection] New connection established.
[00:13:46] [127.0.0.1][b4abf3d3][ExtensionHostConnection] <377> Launched Extension Host Process.
[00:13:50] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[00:14:01] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8986f1]

goroutine 467 [running]:
http_reverse_proxy/client.sendHttpRequestAndReplyHttpResponse(0x1616dffc225d8695?, 0xc1309171df8f6b78?, 0xc000162060, 0xc0000de0c0)
	/builds/hitminer/http_reverse_proxy/client/http_client.go:51 +0xb1
created by http_reverse_proxy/client.startHttpClient
	/builds/hitminer/http_reverse_proxy/client/http_client.go:34 +0x1ea
