2023/12/05 13:04:08 failed to dial tcp connection, retrying
[2023-12-05T13:04:09.065Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-12-05T13:04:09.066Z] info  Using user-data-dir ~/.local/share/code-server
====================================>token: 5226c8f3-95f1-4180-a56b-d4ddbf9f9bf1
[2023-12-05T13:04:09.081Z] info  Using config file ~/.config/code-server/config.yaml
[2023-12-05T13:04:09.082Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-12-05T13:04:09.082Z] info    - Authentication is disabled
[2023-12-05T13:04:09.082Z] info    - Not serving HTTPS
[13:04:11] 




[13:04:11] Extension host agent started.
[13:04:12] [127.0.0.1][9adaf885][ManagementConnection] New connection established.
[13:04:13] [127.0.0.1][a3dbca29][ExtensionHostConnection] New connection established.
[13:04:13] [127.0.0.1][a3dbca29][ExtensionHostConnection] <378> Launched Extension Host Process.
[13:04:17] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[13:04:27] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
[2023-12-05T13:06:23.031Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
2023/12/05 14:18:30 exit program after timeout
